services:
  db:
    image: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1283
    volumes:
      - ./db-data:/var/lib/postgresql/data:z
    networks:
      - backendNetwork

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:80
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:PostgreSqlConnection=User Id=postgres;Server=db,5432;Database=dotnet;Integrated Security=true;"
    depends_on:
      - db
    networks:
      - backendNetwork

volumes:
  db-data:

networks:
  backendNetwork:
    driver: bridge
